### ISSUE TITLE
Integrate web server, GraphQL layer, and data layer

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#1145]
- We ideally want to keep GraphQL usage on the web API
  - We're using GraphQL syntax to define our data models (regardless of the outcome of this issue) so it would be nice to stay consistent, and other projects at Fuel use GraphQL
- In order to avoid https://github.com/FuelLabs/fuel-indexer/issues/1066, we need to figure out some way to integrate our web server (axum), our GraphQL usage (async-graphql), and our data layer (sqlx)
- The Graph solved for this by just hand-rolling _everything_
  - https://github.com/graphprotocol/graph-node/blob/master/graphql
- We will most likely have to do the same
- Although we maybe won't be able to use their `graph-graphql` crate, we could most definitely take inspiration from how they're doing things

### Tasks
- [x] https://github.com/FuelLabs/fuel-indexer/issues/1325
- [ ] ~~https://github.com/FuelLabs/fuel-indexer/issues/1310~~
- [ ] https://github.com/FuelLabs/fuel-indexer/issues/931
- [ ] https://github.com/FuelLabs/fuel-indexer/issues/960
- [ ] https://github.com/FuelLabs/fuel-indexer/issues/858

**Comment by ra0x3** [comment]
Steps
- [ ] https://github.com/FuelLabs/fuel-indexer/issues/846

Will add more steps as we find them

**Comment by ra0x3** [comment]
@deekerno Just an FYI
- Keep in mind the other two smaller issues in this larger issue ☝🏼 
- I closed them out but we should still integrate them into whatever work you do.
- They are:
  - Usage of `camelCase` field definition names in the schema (e.g., `account_id` becomes `accountId`)
  - Using `snake_case` table names for type definitions that are `PascalCased` (e.g., `indexmetadataentity` becomes `index_metadata_entity`
