### ISSUE TITLE
Holiday milestone (12/31)

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#353]
https://github.com/FuelLabs/pm/issues/36

- Bugs
  - [x] https://github.com/FuelLabs/fuel-indexer/issues/369 
  - [x] https://github.com/FuelLabs/fuel-indexer/issues/289
  - [ ] https://github.com/FuelLabs/fuel-indexer/issues/408 (blocked ❌ )
 
- Testing & code quality
  - [x] https://github.com/FuelLabs/fuel-indexer/issues/269
  - [ ] https://github.com/FuelLabs/fuel-indexer/issues/288 (blocked ❌ )
  - [x] https://github.com/FuelLabs/fuel-indexer/issues/391 
  - [x] https://github.com/FuelLabs/fuel-indexer/issues/344
  - [x] https://github.com/FuelLabs/fuel-indexer/issues/334
 
- New functionality
  - [ ] https://github.com/FuelLabs/fuel-indexer/issues/300 (blocked ❌ )
  - [x] https://github.com/FuelLabs/fuel-indexer/issues/389
  - [ ] https://github.com/FuelLabs/fuel-indexer/issues/390
  - [x] https://github.com/FuelLabs/fuel-indexer/issues/396
  - [x] https://github.com/FuelLabs/fuel-indexer/issues/410

- Documentation
  - [x] https://github.com/FuelLabs/fuel-indexer/issues/393
  - [x] https://github.com/FuelLabs/fuel-indexer/issues/394
  - [x] https://github.com/FuelLabs/fuel-indexer/issues/398
