### ISSUE TITLE
Finalize mdbook for Holiday Milestone (12/31)

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#398]
- [x] Change the "Receipts" section to "What can I index" and better explain what types/data users can index
- [x] Add explanations for Tx data -- copy it from the fuel-tx docs here https://github.com/FuelLabs/fuel-specs/tree/master/src/protocol/tx_format
- [ ] Add specific setup details according to platform (we sort've have this but it makes some assumptions. no assumptions should be made)
  - This is a PITA but no avoiding it
- [x] Add details on how to get setup with a database (postgres & sqlite)
  - This should be added to the Quickstart too
- [ ] All example usage should use the plugin where possible
- [x] Add a section to "Components" that explains how to get started with the Fuel node
