### ISSUE TITLE
Beta-4 Milestone

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#529]
### Docs
- [ ] https://github.com/FuelLabs/fuel-indexer/issues/489

### Sway support
- [ ] https://github.com/FuelLabs/fuel-indexer/issues/503 (blocked ❌)

### Upgrade dependencies
- [ ] https://github.com/FuelLabs/fuel-indexer/issues/423 (blocked ❌)

### Fix hacks
- [ ] https://github.com/FuelLabs/fuel-indexer/issues/408 (blocked ❌)

### New functionality
- [ ] https://github.com/FuelLabs/fuel-indexer/issues/460
- [ ] https://github.com/FuelLabs/fuel-indexer/issues/525
- [ ] https://github.com/FuelLabs/fuel-indexer/issues/382
- [ ] https://github.com/FuelLabs/fuel-indexer/issues/251
- [ ] https://github.com/FuelLabs/fuel-deployment/issues/106
- [ ] https://github.com/FuelLabs/fuel-indexer/issues/240
