### ISSUE TITLE
Update documentation for beta-4 milestone

### ISSUE THREAD

**Issue by deekerno** [FuelLabs/fuel-indexer#566]
We should ensure that our documentation is up to date with information about recently added features associated with our beta-4 milestone. Said information doesn't have to be completely fleshed out, but we should make it a point to include at least something about each part.

Running list of things of undocumented features that are implemented or waiting for review:
- [ ] Native execution
- [x] Optional schema fields
- [x] `forc postgres` (added as part of #558)
- [x] ~Nested API queries (added as part of #563)~
- [ ] New Sway types (?)
- [x] Option to start local node with indexer binary (added as part of #551)
- [x] Add information about changing the contract ID in a manifest after editing the Sway code

**Comment by deekerno** [comment]
Work is being tracked in the [`deekerno/566-update-book-for-beta-4`](https://github.com/FuelLabs/fuel-indexer/tree/deekerno/566-update-book-for-beta-4) branch.
